cluster.name: "code-du-travail-data-elasticsearch"
node.name: "code-du-travail-data-elasticsearch-single-node"

# Use single node discovery in order for the node to elect itself master and not join a cluster with any other node.
# https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
discovery.type: single-node

# https://github.com/mobz/elasticsearch-head#enable-cors-in-elasticsearch
http.cors.enabled: true
http.cors.allow-origin: 'https://socialgouv.github.io'
